# Generated by Django 5.2.4 on 2025-08-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='diary/picture/', verbose_name='写真'),
        ),
    ]

#データベースに項目を増やしたら必ずマイグレーションする！